version: '3.8'

services:

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - API_ENDPOINT=http://127.0.0.1:5000
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: app/views/web/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - API_GATEWAY_URL=http://api-gateway:5000
    networks:
      - app-network
    depends_on:
      - api-gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge