version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: app/views/web/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - BACKEND_URL=http://host.docker.internal:5000
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mobile:
    build:
      context: .
      dockerfile: app/views/mobile/Dockerfile
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ENVIRONMENT=development
      - BACKEND_URL=http://host.docker.internal:5000
      - DISPLAY=host.docker.internal:0.0
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge 